{{- if and .Values.neo4j.enabled .Values.neo4j.persistence }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j-pv
  labels:
    app: {{ template "amundsen.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ default "3Gi" .Values.neo4j.persistence.size }}
  volumeMode: Filesystem
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.neo4j.persistence.volumeHandle }}
{{- end }}